version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
      - minio
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravelminio  
      - DB_USERNAME=root
      - DB_PASSWORD=080907

  db:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=laravelminio  
      - MYSQL_ROOT_PASSWORD=080907

  minio:
    image: minio/minio:latest
    container_name: minio_storage
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio-data:/data
    environment:
      - MINIO_ROOT_USER=anandisaputra
      - MINIO_ROOT_PASSWORD=anandi12
    command: server --console-address ":9001" /data
volumes:
  mysql_data:
  minio_storage: